import { Product, PortfolioProject, ServiceItem, Category, Review, Order } from '@/types/database';

export const DEMO_CATEGORIES: Category[] = [
  { id: 'cat-1', name: 'Fine-Art Canvas Paintings', slug: 'canvas-paintings', description: 'Original oil, acrylic, and textured canvas paintings', type: 'product', created_at: new Date().toISOString() },
  { id: 'cat-2', name: 'African Portraiture & Figurative Art', slug: 'portrait-art', description: 'Expressive portrait paintings and life-study canvas works', type: 'product', created_at: new Date().toISOString() },
  { id: 'cat-3', name: 'Landscape & Heritage Scenery', slug: 'landscape-art', description: 'Vibrant African landscape paintings and natural scenery', type: 'product', created_at: new Date().toISOString() },
  { id: 'cat-4', name: 'Interior Murals & Contemporary Fine Art', slug: 'wall-art', description: 'Handcrafted wall paintings and contemporary decorative canvas art', type: 'product', created_at: new Date().toISOString() },
  { id: 'pcat-1', name: 'Portrait Painting', slug: 'portrait-painting', description: 'Expressive oil and acrylic human portraiture', type: 'portfolio', created_at: new Date().toISOString() },
  { id: 'pcat-2', name: 'Landscape Painting', slug: 'landscape-painting', description: 'Vibrant natural vistas and African scenery', type: 'portfolio', created_at: new Date().toISOString() },
  { id: 'pcat-3', name: 'Life & Cultural Art', slug: 'life-image-painting', description: 'Capturing cultural essence and authentic life scenes', type: 'portfolio', created_at: new Date().toISOString() },
  { id: 'pcat-4', name: 'Interior & Wall Murals', slug: 'interior-wall-painting', description: 'Custom painted interiors, feature walls, and architectural murals', type: 'portfolio', created_at: new Date().toISOString() },
  { id: 'pcat-5', name: 'Abstract & Textured Canvas', slug: 'abstract-canvas', description: 'Rich textured palette knife paintings and geometric abstractions', type: 'portfolio', created_at: new Date().toISOString() },
];

export const DEMO_PRODUCTS: Product[] = [
  // SECTION 1: FOUNDER PAINTINGS (usr-admin-master)
  {
    id: 'prod-1',
    artist_id: 'usr-admin-master',
    artist_name: 'Abdulmajeed Olasunkanmi O.',
    title: 'Grace & Dignity — Oil Portrait on Linen Canvas',
    slug: 'grace-dignity-oil-portrait',
    description: 'An original oil painting capturing African posture, regal composure, and subtle lighting nuances. Layered with rich pigments on 400gsm stretched linen canvas. Includes certificate of authenticity signed by Abdulmajeed Olasunkanmi O.',
    price: 185000,
    discount_price: 155000,
    category_id: 'cat-2',
    category: DEMO_CATEGORIES[1],
    is_digital: false,
    stock: 1,
    is_featured: true,
    is_published: true,
    specifications: { 'Dimensions': '30 x 40 inches (76 x 101 cm)', 'Medium': 'Oil on Stretched Linen Canvas', 'Frame': 'Solid Natural Teak Floating Frame', 'Authenticity': 'Hand-Signed Certificate Included' },
    images: [
      { id: 'img-1-1', product_id: 'prod-1', image_url: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=1000&auto=format&fit=crop&q=80', alt_text: 'Grace & Dignity Oil Portrait', display_order: 1 },
    ],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-2',
    artist_id: 'usr-admin-master',
    artist_name: 'Abdulmajeed Olasunkanmi O.',
    title: 'Lekki Coastal Sunset — Expressive Landscape Oil',
    slug: 'lekki-coastal-sunset-oil',
    description: 'A study of golden twilight over the Atlantic coastline of Lagos. Textured brushwork and layered glazing produce a warm, calming atmosphere suitable for living and studio spaces.',
    price: 160000,
    discount_price: 135000,
    category_id: 'cat-3',
    category: DEMO_CATEGORIES[2],
    is_digital: false,
    stock: 1,
    is_featured: true,
    is_published: true,
    specifications: { 'Dimensions': '28 x 42 inches (71 x 106 cm)', 'Medium': 'Oil on Heavy Cotton Canvas', 'Artist': 'Abdulmajeed Olasunkanmi O.', 'Condition': 'Original Signed Work' },
    images: [
      { id: 'img-2-1', product_id: 'prod-2', image_url: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=1000&auto=format&fit=crop&q=80', alt_text: 'Lekki Coastal Sunset Canvas', display_order: 1 },
    ],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-3',
    artist_id: 'usr-admin-master',
    artist_name: 'Abdulmajeed Olasunkanmi O.',
    title: 'Heritage Rythms — Figurative Life Painting',
    slug: 'heritage-rythms-life-painting',
    description: 'Capturing the dynamic energy and rhythm of everyday communal life. Painted with earthy ochres, deep umbers, and subtle indigo washes on fine canvas.',
    price: 145000,
    discount_price: 120000,
    category_id: 'cat-1',
    category: DEMO_CATEGORIES[0],
    is_digital: false,
    stock: 2,
    is_featured: false,
    is_published: true,
    specifications: { 'Dimensions': '24 x 36 inches (60 x 91 cm)', 'Medium': 'Acrylic & Oil Glaze on Canvas', 'Finish': 'UV Satin Protective Varnish' },
    images: [
      { id: 'img-3-1', product_id: 'prod-3', image_url: 'https://images.unsplash.com/photo-1578926375605-eaf7559b1458?w=1000&auto=format&fit=crop&q=80', alt_text: 'Heritage Rythms Painting', display_order: 1 },
    ],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-4',
    artist_id: 'usr-admin-master',
    artist_name: 'Abdulmajeed Olasunkanmi O.',
    title: 'The Elder’s Wisdom — Classical African Portraiture',
    slug: 'elders-wisdom-african-portrait',
    description: 'An intimate close-up portrait exploring texture, character, and depth of expression. Masterful handling of light and skin tones against a dark minimalist background.',
    price: 175000,
    discount_price: 145000,
    category_id: 'cat-2',
    category: DEMO_CATEGORIES[1],
    is_digital: false,
    stock: 1,
    is_featured: true,
    is_published: true,
    specifications: { 'Dimensions': '32 x 40 inches (81 x 101 cm)', 'Medium': 'Oil on Cotton Canvas', 'Authenticity': 'Hand-Signed Certificate' },
    images: [
      { id: 'img-4-1', product_id: 'prod-4', image_url: 'https://images.unsplash.com/photo-1577083552431-6e5fd01aa342?w=1000&auto=format&fit=crop&q=80', alt_text: 'The Elder’s Wisdom Portrait', display_order: 1 },
    ],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },

  // SECTION 2: CHIOMA ADEBAYO (usr-artist-1)
  {
    id: 'prod-5',
    artist_id: 'usr-artist-1',
    artist_name: 'Chioma Adebayo',
    title: 'Gele in Ochre — African Headwrap Portrait',
    slug: 'gele-in-ochre-portrait',
    description: 'A striking portrait celebrating the sculptural beauty of the traditional Nigerian Gele headwrap in warm ochre, gold leaf, and deep mahogany pigments.',
    price: 135000,
    discount_price: 115000,
    category_id: 'cat-2',
    category: DEMO_CATEGORIES[1],
    is_digital: false,
    stock: 1,
    is_featured: true,
    is_published: true,
    specifications: { 'Dimensions': '30 x 30 inches (76 x 76 cm)', 'Medium': 'Oil & Gold Leaf on Canvas', 'Artist': 'Chioma Adebayo' },
    images: [
      { id: 'img-5-1', product_id: 'prod-5', image_url: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=1000&auto=format&fit=crop&q=80', alt_text: 'Gele in Ochre Portrait', display_order: 1 },
    ],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-6',
    artist_id: 'usr-artist-1',
    artist_name: 'Chioma Adebayo',
    title: 'Motherhood Serenade — Emotive Figurative Canvas',
    slug: 'motherhood-serenade-canvas',
    description: 'A tender portrayal of maternal affection crafted with soft pastel glazes over textured oil underpainting. Brings tranquility and warmth to any living environment.',
    price: 120000,
    discount_price: 105000,
    category_id: 'cat-1',
    category: DEMO_CATEGORIES[0],
    is_digital: false,
    stock: 2,
    is_featured: false,
    is_published: true,
    specifications: { 'Dimensions': '24 x 32 inches (60 x 81 cm)', 'Medium': 'Oil & Acrylic on Canvas', 'Artist': 'Chioma Adebayo' },
    images: [
      { id: 'img-6-1', product_id: 'prod-6', image_url: 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=1000&auto=format&fit=crop&q=80', alt_text: 'Motherhood Serenade', display_order: 1 },
    ],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-7',
    artist_id: 'usr-artist-1',
    artist_name: 'Chioma Adebayo',
    title: 'Adire Symphony — Textile Pattern Painting',
    slug: 'adire-symphony-painting',
    description: 'Contemporary interpretation of indigo Adire textile geometry painted with layered acrylic washes and copper leaf highlights.',
    price: 95000,
    discount_price: 85000,
    category_id: 'cat-4',
    category: DEMO_CATEGORIES[3],
    is_digital: false,
    stock: 3,
    is_featured: false,
    is_published: true,
    specifications: { 'Dimensions': '20 x 28 inches (50 x 71 cm)', 'Medium': 'Acrylic on Cotton Canvas', 'Artist': 'Chioma Adebayo' },
    images: [
      { id: 'img-7-1', product_id: 'prod-7', image_url: 'https://images.unsplash.com/photo-1547891654-e66ed7ebb968?w=1000&auto=format&fit=crop&q=80', alt_text: 'Adire Symphony Canvas', display_order: 1 },
    ],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },

  // SECTION 3: BABAJIDE ADELEKE (usr-artist-2)
  {
    id: 'prod-8',
    artist_id: 'usr-artist-2',
    artist_name: 'Babajide Adeleke',
    title: 'Savannah Twilight — Panoramic Landscape Painting',
    slug: 'savannah-twilight-landscape',
    description: 'An expansive panoramic view of West African acacia woodland bathed in the deep crimson and amber light of late afternoon sunset.',
    price: 170000,
    discount_price: 140000,
    category_id: 'cat-3',
    category: DEMO_CATEGORIES[2],
    is_digital: false,
    stock: 1,
    is_featured: true,
    is_published: true,
    specifications: { 'Dimensions': '36 x 48 inches (91 x 121 cm)', 'Medium': 'Heavy Impasto Acrylic & Oil', 'Artist': 'Babajide Adeleke' },
    images: [
      { id: 'img-8-1', product_id: 'prod-8', image_url: 'https://images.unsplash.com/photo-1582561424760-0321d75e81fa?w=1000&auto=format&fit=crop&q=80', alt_text: 'Savannah Twilight Landscape', display_order: 1 },
    ],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-9',
    artist_id: 'usr-artist-2',
    artist_name: 'Babajide Adeleke',
    title: 'Rainforest Canopy — Textured Flora Study',
    slug: 'rainforest-canopy-textured-painting',
    description: 'Thick palette knife application depicting lush tropical foliage and dappled tropical light from the Oban forest ranges.',
    price: 115000,
    discount_price: 98000,
    category_id: 'cat-3',
    category: DEMO_CATEGORIES[2],
    is_digital: false,
    stock: 2,
    is_featured: false,
    is_published: true,
    specifications: { 'Dimensions': '24 x 36 inches (60 x 91 cm)', 'Medium': 'Palette Knife Oil on Canvas', 'Artist': 'Babajide Adeleke' },
    images: [
      { id: 'img-9-1', product_id: 'prod-9', image_url: 'https://images.unsplash.com/photo-1579783902264-e85489f654b4?w=1000&auto=format&fit=crop&q=80', alt_text: 'Rainforest Canopy Study', display_order: 1 },
    ],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },

  // SECTION 4: AMARA OKAFOR (usr-artist-3)
  {
    id: 'prod-10',
    artist_id: 'usr-artist-3',
    artist_name: 'Amara Okafor',
    title: 'Echoes of Uli — Contemporary Heritage Mural Canvas',
    slug: 'echoes-of-uli-mural-canvas',
    description: 'Inspired by traditional Igbo Uli body and wall mural motifs. Bold rhythmic black line work juxtaposed against textured saffron and terracotta grounds.',
    price: 150000,
    discount_price: 125000,
    category_id: 'cat-4',
    category: DEMO_CATEGORIES[3],
    is_digital: false,
    stock: 2,
    is_featured: true,
    is_published: true,
    specifications: { 'Dimensions': '30 x 45 inches (76 x 114 cm)', 'Medium': 'Natural Pigments & Acrylic on Stretched Linen', 'Artist': 'Amara Okafor' },
    images: [
      { id: 'img-10-1', product_id: 'prod-10', image_url: 'https://images.unsplash.com/photo-1576769267415-9642010aa962?w=1000&auto=format&fit=crop&q=80', alt_text: 'Echoes of Uli Canvas', display_order: 1 },
    ],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-11',
    artist_id: 'usr-artist-3',
    artist_name: 'Amara Okafor',
    title: 'Market Day Radiance — Figurative Life Composition',
    slug: 'market-day-radiance-composition',
    description: 'An expressive depiction of market traders in lively conversation. Rich, energetic color contrasts celebrate enterprise and community spirit.',
    price: 130000,
    discount_price: 110000,
    category_id: 'cat-2',
    category: DEMO_CATEGORIES[1],
    is_digital: false,
    stock: 2,
    is_featured: false,
    is_published: true,
    specifications: { 'Dimensions': '24 x 36 inches (60 x 91 cm)', 'Medium': 'Oil on Canvas', 'Artist': 'Amara Okafor' },
    images: [
      { id: 'img-11-1', product_id: 'prod-11', image_url: 'https://images.unsplash.com/photo-1580136579312-94651dfd596d?w=1000&auto=format&fit=crop&q=80', alt_text: 'Market Day Radiance', display_order: 1 },
    ],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },

  // SECTION 5: KOFI MENSAH (usr-artist-4)
  {
    id: 'prod-12',
    artist_id: 'usr-artist-4',
    artist_name: 'Kofi Mensah',
    title: 'Ancestral Resonance — Earth-Tone Abstract Painting',
    slug: 'ancestral-resonance-abstract',
    description: 'Heavy impasto painting using raw sienna, burnt umber, and charcoal glazes to convey timeless architectural textures and ancestral memory.',
    price: 140000,
    discount_price: 118000,
    category_id: 'cat-4',
    category: DEMO_CATEGORIES[3],
    is_digital: false,
    stock: 1,
    is_featured: true,
    is_published: true,
    specifications: { 'Dimensions': '36 x 36 inches (91 x 91 cm)', 'Medium': 'Oil & Charcoal on Canvas', 'Artist': 'Kofi Mensah' },
    images: [
      { id: 'img-12-1', product_id: 'prod-12', image_url: 'https://images.unsplash.com/photo-1579783901586-7880cb4cd40a?w=1000&auto=format&fit=crop&q=80', alt_text: 'Ancestral Resonance Canvas', display_order: 1 },
    ],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
];

export const DEMO_PORTFOLIO: PortfolioProject[] = [
  {
    id: 'port-1',
    title: 'Monarch’s Presence — Commissioned Presidential Portrait',
    slug: 'monarchs-presence-portrait',
    description: 'A life-size oil on canvas portrait commission created with classical glazing techniques, capturing royal regalia and dignity with remarkable precision.',
    client_name: 'Royal Heritage Foundation',
    category_id: 'pcat-1',
    category: DEMO_CATEGORIES[4],
    cover_image: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=1200&auto=format&fit=crop&q=80',
    tools_used: ['Master Oil Glazes', 'Belgian Stretched Linen', 'Damar Varnish', 'Custom Teak Framing'],
    is_featured: true,
    is_published: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'port-2',
    title: 'Eko Atlantic Vistas — Large-Format Atmospheric Landscape',
    slug: 'eko-atlantic-vistas-landscape',
    description: 'An expansive landscape capturing the meeting point of maritime clouds, coastal tide lines, and Lagos urban architecture.',
    client_name: 'Victoria Island Corporate Lounge',
    category_id: 'pcat-2',
    category: DEMO_CATEGORIES[5],
    cover_image: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=1200&auto=format&fit=crop&q=80',
    tools_used: ['Impasto Oil Technique', 'Large Format Canvas', 'Palette Knife Blending'],
    is_featured: true,
    is_published: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'port-3',
    title: 'Sons of the Soil — Figurative Cultural Mural',
    slug: 'sons-of-the-soil-mural',
    description: 'A 20-foot feature wall painting commissioned for a luxury residence, exploring traditional drumming, communal harvest, and cultural harmony.',
    client_name: 'Ikoyi Private Residence',
    category_id: 'pcat-4',
    category: DEMO_CATEGORIES[7],
    cover_image: 'https://images.unsplash.com/photo-1578926375605-eaf7559b1458?w=1200&auto=format&fit=crop&q=80',
    tools_used: ['Interior Mural Acrylics', 'Gold Leaf Accents', 'Polymer Protective Coating'],
    is_featured: true,
    is_published: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'port-4',
    title: 'The Matriarch — Fine Art Portrait Study',
    slug: 'the-matriarch-portrait-study',
    description: 'An expressive oil study celebrating strength, wisdom, and grace across generations of West African women.',
    client_name: 'Contemporary African Art Collection',
    category_id: 'pcat-1',
    category: DEMO_CATEGORIES[4],
    cover_image: 'https://images.unsplash.com/photo-1577083552431-6e5fd01aa342?w=1200&auto=format&fit=crop&q=80',
    tools_used: ['Layered Oil Glazing', 'Raw Pigments', 'Fine Cotton Canvas'],
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'port-5',
    title: 'Dusk Over the Plateau — Highland Landscape',
    slug: 'dusk-over-plateau-landscape',
    description: 'Capturing misty hills, granite rock formations, and serene twilight tones in the central Nigerian highlands.',
    client_name: 'Abuja Arts Pavilion',
    category_id: 'pcat-2',
    category: DEMO_CATEGORIES[5],
    cover_image: 'https://images.unsplash.com/photo-1582561424760-0321d75e81fa?w=1200&auto=format&fit=crop&q=80',
    tools_used: ['Wet-on-Wet Oil Painting', 'Linen Canvas', 'Satin Varnish Finish'],
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'port-6',
    title: 'Earth Harmonies — Textured Gallery Abstract',
    slug: 'earth-harmonies-abstract',
    description: 'A large abstract work incorporating mineral sands, natural earth pigments, and expressive charcoal contours.',
    client_name: 'Lagos Modern Atelier',
    category_id: 'pcat-5',
    category: DEMO_CATEGORIES[8],
    cover_image: 'https://images.unsplash.com/photo-1579783901586-7880cb4cd40a?w=1200&auto=format&fit=crop&q=80',
    tools_used: ['Mixed Media Pigments', 'Heavy Canvas', 'Protective Wax Glaze'],
    is_featured: false,
    is_published: true,
    created_at: new Date().toISOString(),
  }
];

export const DEMO_SERVICES: ServiceItem[] = [
  {
    id: 'srv-1',
    title: 'Bespoke Oil Portrait Painting',
    slug: 'bespoke-oil-portrait-painting',
    description: 'Custom, hand-painted life or photographic portrait on premium Belgian linen canvas. Crafted to become an enduring family heirloom.',
    starting_price: 150000,
    delivery_time_days: 18,
    image_url: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=800&auto=format&fit=crop&q=80',
    features: ['Initial composition preview', 'Hand-signed original canvas', 'High-grade protective UV varnish', 'Certificate of Authenticity'],
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'srv-2',
    title: 'Custom Architectural & Interior Wall Murals',
    slug: 'interior-wall-murals',
    description: 'Transform residential, hospitality, or corporate walls into memorable works of art with bespoke hand-painted murals.',
    starting_price: 250000,
    delivery_time_days: 10,
    image_url: 'https://images.unsplash.com/photo-1578926375605-eaf7559b1458?w=800&auto=format&fit=crop&q=80',
    features: ['On-site spatial consultation', 'Color harmony matching', 'Washable, durable fine art paints', 'Protective weather-resistant coat'],
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'srv-3',
    title: 'Landscape & Heritage Scene Commission',
    slug: 'landscape-heritage-commission',
    description: 'Commission an original landscape painting representing ancestral lands, favorite scenic vistas, or memorable spaces.',
    starting_price: 120000,
    delivery_time_days: 14,
    image_url: 'https://images.unsplash.com/photo-1582561424760-0321d75e81fa?w=800&auto=format&fit=crop&q=80',
    features: ['Custom dimensions up to 6 feet', 'Choice of palette and mood', 'Floating wood frame options', 'Nationwide and global delivery'],
    is_active: true,
    created_at: new Date().toISOString(),
  }
];

export const DEMO_ORDERS: Order[] = [
  {
    id: 'ord-101',
    order_number: 'SKO-9421',
    user_id: 'usr-customer-1',
    customer_email: 'collector@skartwork.com',
    customer_name: 'Dr. Tunde Alabi',
    total_amount: 155000,
    discount_amount: 0,
    delivery_fee: 0,
    net_amount: 155000,
    order_status: 'Completed',
    payment_status: 'Paid',
    payment_provider: 'paystack',
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    items: [
      {
        id: 'ord-item-1',
        order_id: 'ord-101',
        product_id: 'prod-1',
        product_title: 'Grace & Dignity — Oil Portrait on Linen Canvas',
        is_digital: false,
        quantity: 1,
        price: 155000,
        product: DEMO_PRODUCTS[0],
      }
    ]
  },
  {
    id: 'ord-102',
    order_number: 'SKO-9428',
    user_id: 'usr-customer-2',
    customer_email: 'adeyemi@skartwork.com',
    customer_name: 'Mrs. Folake Adeyemi',
    total_amount: 115000,
    discount_amount: 0,
    delivery_fee: 0,
    net_amount: 115000,
    order_status: 'Processing',
    payment_status: 'Paid',
    payment_provider: 'flutterwave',
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    items: [
      {
        id: 'ord-item-2',
        order_id: 'ord-102',
        product_id: 'prod-5',
        product_title: 'Gele in Ochre — African Headwrap Portrait',
        is_digital: false,
        quantity: 1,
        price: 115000,
        product: DEMO_PRODUCTS[4],
      }
    ]
  }
];

export const DEMO_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    product_id: 'prod-1',
    user_id: 'usr-1',
    user_name: 'Dr. Tunde Alabi',
    rating: 5,
    comment: 'Exceptional oil portrait work! The likeness and color depth exceeded our expectations.',
    is_verified_purchase: true,
    status: 'approved',
    created_at: new Date().toISOString(),
  },
  {
    id: 'rev-2',
    product_id: 'prod-5',
    user_id: 'usr-2',
    user_name: 'Mrs. Folake Adeyemi',
    rating: 5,
    comment: 'Immaculate painting delivered on schedule in protective wooden crating. Certified authentic fine art.',
    is_verified_purchase: true,
    status: 'approved',
    created_at: new Date().toISOString(),
  }
];
