import { Product, PortfolioProject, ServiceItem, Category, Review, Order } from '@/types/database';

export const DEMO_CATEGORIES: Category[] = [
  { id: 'cat-1', name: 'Fine-Art Canvas Paintings', slug: 'canvas-paintings', description: 'Original oil, acrylic, and textured canvas artwork', type: 'product', created_at: new Date().toISOString() },
  { id: 'cat-2', name: 'Portrait & Life Art Prints', slug: 'portrait-art', description: 'High-detail portrait paintings and life-image art pieces', type: 'product', created_at: new Date().toISOString() },
  { id: 'cat-3', name: 'Landscape & Nature Art', slug: 'landscape-art', description: 'Serene landscape paintings and scenic visual compositions', type: 'product', created_at: new Date().toISOString() },
  { id: 'cat-4', name: 'Wall Art & Decorative Pieces', slug: 'wall-art', description: 'Handcrafted wall paintings, decorative art, and sculptures', type: 'product', created_at: new Date().toISOString() },
  { id: 'pcat-1', name: 'Portrait Painting', slug: 'portrait-painting', description: 'Expressive oil and acrylic human portraiture', type: 'portfolio', created_at: new Date().toISOString() },
  { id: 'pcat-2', name: 'Landscape Painting', slug: 'landscape-painting', description: 'Vibrant natural vistas and outdoor scenery', type: 'portfolio', created_at: new Date().toISOString() },
  { id: 'pcat-3', name: 'Life-Image Painting', slug: 'life-image-painting', description: 'Capturing human emotions and authentic life scenes', type: 'portfolio', created_at: new Date().toISOString() },
  { id: 'pcat-4', name: 'Interior & Wall Painting', slug: 'interior-wall-painting', description: 'Custom painted interiors, feature walls, and murals', type: 'portfolio', created_at: new Date().toISOString() },
  { id: 'pcat-5', name: 'Sculpture & Decorative Works', slug: 'sculpture-decorative', description: 'Three-dimensional art forms and artistic sculptures', type: 'portfolio', created_at: new Date().toISOString() },
];

export const DEMO_PRODUCTS: Product[] = [
  // SECTION 1: FINE-ART CANVAS PAINTINGS (8 ITEMS)
  {
    id: 'prod-1',
    title: 'Grace & Elegance — Oil Portrait Painting (Canvas Edition)',
    slug: 'grace-elegance-oil-portrait',
    description: 'A captivating oil painting capturing human emotion, posture, and subtle lighting contrast. Crafted with rich layers of oil paint on heavy 400gsm cotton canvas. Includes Certificate of Authenticity signed by Abdulmajeed Olasunkanmi O..',
    price: 125000,
    discount_price: 95000,
    category_id: 'cat-1',
    category: DEMO_CATEGORIES[0],
    is_digital: false,
    stock: 5,
    is_featured: true,
    is_published: true,
    specifications: { 'Dimensions': '30 x 40 inches (76 x 101 cm)', 'Medium': 'Oil on Stretched Cotton Canvas', 'Frame': 'Teak Wood Floating Frame', 'Authenticity': 'Hand-Signed Certificate Included' },
    images: [
      { id: 'img-1-1', product_id: 'prod-1', image_url: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=1000&auto=format&fit=crop&q=80', alt_text: 'Oil Portrait Painting Preview', display_order: 1 },
    ],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-3',
    title: 'Serene Reflections — Life-Image Oil Study',
    slug: 'serene-reflections-life-image-painting',
    description: 'A contemplative life-image painting reflecting natural light falling across textured surfaces. Designed to bring warmth, stillness, and artistic character to high-end interior spaces.',
    price: 110000,
    discount_price: 88000,
    category_id: 'cat-1',
    category: DEMO_CATEGORIES[0],
    is_digital: false,
    stock: 4,
    is_featured: true,
    is_published: true,
    specifications: { 'Dimensions': '24 x 36 inches (60 x 91 cm)', 'Medium': 'Heavy Impasto Oil on Canvas', 'Artist': 'Abdulmajeed Olasunkanmi O.', 'Condition': 'Original Signed Piece' },
    images: [
      { id: 'img-3-1', product_id: 'prod-3', image_url: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=1000&auto=format&fit=crop&q=80', alt_text: 'Serene Reflections Canvas', display_order: 1 },
    ],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-6',
    title: 'Crimson & Gold Abstraction — Textured Oil Canvas',
    slug: 'crimson-gold-abstraction-canvas',
    description: 'Dynamic expressionist canvas featuring vibrant crimson pigment blended with shimmering gold accents. Palette knife application gives high tactile depth and visual energy.',
    price: 135000,
    discount_price: 110000,
    category_id: 'cat-1',
    category: DEMO_CATEGORIES[0],
    is_digital: false,
    stock: 3,
    is_featured: false,
    is_published: true,
    specifications: { 'Dimensions': '36 x 36 inches (91 x 91 cm)', 'Medium': 'Oil & Gold Leaf on Linen', 'Finish': 'UV Satin Protective Varnish' },
    images: [
      { id: 'img-6-1', product_id: 'prod-6', image_url: 'https://images.unsplash.com/photo-1578926375605-eaf7559b1458?w=1000&auto=format&fit=crop&q=80', alt_text: 'Crimson Abstraction Canvas', display_order: 1 },
    ],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-7',
    title: 'Celestial Harmony — Acrylic & Metallic Leaf Canvas',
    slug: 'celestial-harmony-canvas',
    description: 'An ethereal fine art composition exploring cosmic forms, soft indigo gradients, and hand-gilded copper leaf detailing.',
    price: 98000,
    discount_price: 82000,
    category_id: 'cat-1',
    category: DEMO_CATEGORIES[0],
    is_digital: false,
    stock: 6,
    is_featured: false,
    is_published: true,
    specifications: { 'Dimensions': '24 x 30 inches (60 x 76 cm)', 'Medium': 'Acrylic & Metallic Leaf', 'Authenticity': 'Signed Certificate' },
    images: [
      { id: 'img-7-1', product_id: 'prod-7', image_url: 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=1000&auto=format&fit=crop&q=80', alt_text: 'Celestial Harmony', display_order: 1 },
    ],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-8',
    title: 'Whispers of Dawn — Pastel & Oil Blend Canvas',
    slug: 'whispers-of-dawn-canvas',
    description: 'Soft pastel hues seamlessly blended with fine oil glazes depicting the gentle light of morning break across organic forms.',
    price: 105000,
    discount_price: 89000,
    category_id: 'cat-1',
    category: DEMO_CATEGORIES[0],
    is_digital: false,
    stock: 4,
    is_featured: false,
    is_published: true,
    specifications: { 'Dimensions': '28 x 40 inches (71 x 101 cm)', 'Medium': 'Oil & Soft Pastel Glaze' },
    images: [
      { id: 'img-8-1', product_id: 'prod-8', image_url: 'https://images.unsplash.com/photo-1582561424760-0321d75e81fa?w=1000&auto=format&fit=crop&q=80', alt_text: 'Whispers of Dawn', display_order: 1 },
    ],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-9',
    title: 'Solitude in Indigo — Contemporary Oil Expression',
    slug: 'solitude-in-indigo-canvas',
    description: 'Deep cobalt, navy, and muted ivory layers in a contemplative abstract study created for modern gallery settings and luxury residences.',
    price: 115000,
    discount_price: 98000,
    category_id: 'cat-1',
    category: DEMO_CATEGORIES[0],
    is_digital: false,
    stock: 5,
    is_featured: false,
    is_published: true,
    specifications: { 'Dimensions': '32 x 48 inches (81 x 122 cm)', 'Medium': 'Heavy Duty Oil on Canvas' },
    images: [
      { id: 'img-9-1', product_id: 'prod-9', image_url: 'https://images.unsplash.com/photo-1579546928686-286c9fbde1ec?w=1000&auto=format&fit=crop&q=80', alt_text: 'Solitude in Indigo', display_order: 1 },
    ],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-10',
    title: 'Golden Radiance — Textured Knife Painting',
    slug: 'golden-radiance-knife-painting',
    description: 'Bold impasto palette knife strokes creating an energetic sunlit motif. Rich texture catches natural room light throughout the day.',
    price: 145000,
    discount_price: 120000,
    category_id: 'cat-1',
    category: DEMO_CATEGORIES[0],
    is_digital: false,
    stock: 3,
    is_featured: false,
    is_published: true,
    specifications: { 'Dimensions': '36 x 48 inches (91 x 122 cm)', 'Medium': 'Impasto Oil Knife Work' },
    images: [
      { id: 'img-10-1', product_id: 'prod-10', image_url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1000&auto=format&fit=crop&q=80', alt_text: 'Golden Radiance', display_order: 1 },
    ],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-11',
    title: 'Eternal Rhythm — Abstract Fine Art Canvas',
    slug: 'eternal-rhythm-fine-art-canvas',
    description: 'Flowing rhythmic curves and warm earthy tones harmonized in a timeless abstract painting.',
    price: 120000,
    discount_price: 99000,
    category_id: 'cat-1',
    category: DEMO_CATEGORIES[0],
    is_digital: false,
    stock: 7,
    is_featured: false,
    is_published: true,
    specifications: { 'Dimensions': '30 x 40 inches (76 x 101 cm)', 'Medium': 'Acrylic & Oil Glaze' },
    images: [
      { id: 'img-11-1', product_id: 'prod-11', image_url: 'https://images.unsplash.com/photo-1579546929662-711aa81148cf?w=1000&auto=format&fit=crop&q=80', alt_text: 'Eternal Rhythm', display_order: 1 },
    ],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },

  // SECTION 2: PORTRAIT & LIFE ART PRINTS (8 ITEMS)
  {
    id: 'prod-12',
    title: 'Royal Legacy — Oil Portrait Painting (Limited Canvas Edition)',
    slug: 'royal-legacy-portrait-edition',
    description: 'Regal oil portrait showcasing dignity, detailed facial tones, and traditional African headwear details. Museum quality print on stretched canvas.',
    price: 150000,
    discount_price: 125000,
    category_id: 'cat-2',
    category: DEMO_CATEGORIES[1],
    is_digital: false,
    stock: 5,
    is_featured: true,
    is_published: true,
    specifications: { 'Dimensions': '30 x 40 inches (76 x 101 cm)', 'Medium': 'Giclée Fine Art Canvas', 'Edition': 'Hand-Signed Limited Edition 1/15' },
    images: [
      { id: 'img-12-1', product_id: 'prod-12', image_url: 'https://images.unsplash.com/photo-1577083552431-6e5fd01aa342?w=1000&auto=format&fit=crop&q=80', alt_text: 'Royal Legacy Portrait', display_order: 1 },
    ],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-13',
    title: 'Contemplation of Youth — Life-Image Canvas Print',
    slug: 'contemplation-youth-life-image',
    description: 'An intimate life-image painting depicting thoughtful expression and warm golden skin highlights.',
    price: 92000,
    discount_price: 78000,
    category_id: 'cat-2',
    category: DEMO_CATEGORIES[1],
    is_digital: false,
    stock: 8,
    is_featured: false,
    is_published: true,
    specifications: { 'Dimensions': '24 x 32 inches (60 x 81 cm)', 'Medium': 'Canvas Print with Hand Varnish' },
    images: [
      { id: 'img-13-1', product_id: 'prod-13', image_url: 'https://images.unsplash.com/photo-1536924940846-227afb31e2a5?w=1000&auto=format&fit=crop&q=80', alt_text: 'Contemplation of Youth', display_order: 1 },
    ],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-14',
    title: 'Heritage & Pride — Figurative Oil Portrait',
    slug: 'heritage-pride-oil-portrait',
    description: 'Powerful figurative oil painting celebrating heritage, strength, and vibrant textile textures.',
    price: 140000,
    discount_price: 118000,
    category_id: 'cat-2',
    category: DEMO_CATEGORIES[1],
    is_digital: false,
    stock: 4,
    is_featured: false,
    is_published: true,
    specifications: { 'Dimensions': '36 x 48 inches (91 x 122 cm)', 'Medium': 'Oil on Linen Canvas' },
    images: [
      { id: 'img-14-1', product_id: 'prod-14', image_url: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=1000&auto=format&fit=crop&q=80', alt_text: 'Heritage & Pride', display_order: 1 },
    ],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-15',
    title: 'Luminance of Grace — Fine Art Life Study',
    slug: 'luminance-grace-life-study',
    description: 'Delicate life-image study in soft ambient lighting, rendering graceful silhouettes and painterly brush strokes.',
    price: 88000,
    discount_price: 72000,
    category_id: 'cat-2',
    category: DEMO_CATEGORIES[1],
    is_digital: false,
    stock: 6,
    is_featured: false,
    is_published: true,
    specifications: { 'Dimensions': '20 x 30 inches (50 x 76 cm)', 'Medium': 'Cotton Canvas Fine Art Edition' },
    images: [
      { id: 'img-15-1', product_id: 'prod-15', image_url: 'https://images.unsplash.com/photo-1577720643272-265f09367456?w=1000&auto=format&fit=crop&q=80', alt_text: 'Luminance of Grace', display_order: 1 },
    ],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-16',
    title: 'Maiden in Golden Light — Portrait Oil Study',
    slug: 'maiden-golden-light-portrait',
    description: 'Rich oil portrait glowing with warm ochre and amber hues.',
    price: 130000,
    discount_price: 105000,
    category_id: 'cat-2',
    category: DEMO_CATEGORIES[1],
    is_digital: false,
    stock: 3,
    is_featured: false,
    is_published: true,
    specifications: { 'Dimensions': '28 x 36 inches (71 x 91 cm)', 'Medium': 'Oil on Stretched Canvas' },
    images: [
      { id: 'img-16-1', product_id: 'prod-16', image_url: 'https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?w=1000&auto=format&fit=crop&q=80', alt_text: 'Maiden in Golden Light', display_order: 1 },
    ],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-17',
    title: 'Silent Reflection — Life-Image Fine Print',
    slug: 'silent-reflection-fine-print',
    description: 'Poetic life scene exploring solitude and inner calmness.',
    price: 85000,
    discount_price: 69000,
    category_id: 'cat-2',
    category: DEMO_CATEGORIES[1],
    is_digital: false,
    stock: 10,
    is_featured: false,
    is_published: true,
    specifications: { 'Dimensions': '24 x 30 inches (60 x 76 cm)', 'Medium': 'Textured Canvas Edition' },
    images: [
      { id: 'img-17-1', product_id: 'prod-17', image_url: 'https://images.unsplash.com/photo-1579783928621-7a13d66a62d1?w=1000&auto=format&fit=crop&q=80', alt_text: 'Silent Reflection', display_order: 1 },
    ],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-18',
    title: 'Visionary Spirit — Expressive Character Portrait',
    slug: 'visionary-spirit-portrait',
    description: 'Bold expressive brushwork capturing intense gaze and character depth.',
    price: 118000,
    discount_price: 99000,
    category_id: 'cat-2',
    category: DEMO_CATEGORIES[1],
    is_digital: false,
    stock: 4,
    is_featured: false,
    is_published: true,
    specifications: { 'Dimensions': '30 x 40 inches (76 x 101 cm)', 'Medium': 'Acrylic & Pastel on Canvas' },
    images: [
      { id: 'img-18-1', product_id: 'prod-18', image_url: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=1000&auto=format&fit=crop&q=80', alt_text: 'Visionary Spirit', display_order: 1 },
    ],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-19',
    title: 'Timeless Dignity — Heritage Oil Portrait',
    slug: 'timeless-dignity-heritage-portrait',
    description: 'Classic portraiture rendering cultural heritage with dignity and craftsmanship.',
    price: 160000,
    discount_price: 135000,
    category_id: 'cat-2',
    category: DEMO_CATEGORIES[1],
    is_digital: false,
    stock: 2,
    is_featured: false,
    is_published: true,
    specifications: { 'Dimensions': '36 x 48 inches (91 x 122 cm)', 'Medium': 'Master Oil on Canvas' },
    images: [
      { id: 'img-19-1', product_id: 'prod-19', image_url: 'https://images.unsplash.com/photo-1578321272176-b7bbc0679853?w=1000&auto=format&fit=crop&q=80', alt_text: 'Timeless Dignity', display_order: 1 },
    ],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },

  // SECTION 3: LANDSCAPE & NATURE ART (8 ITEMS)
  {
    id: 'prod-2',
    title: 'Horizon of Gold & Indigo — Landscape Artwork (Original Fine Art)',
    slug: 'horizon-gold-indigo-landscape',
    description: 'An evocative landscape painting depicting dusk over rolling terrain. Warm gold leaf accents blend harmoniously with deep indigo and cobalt brushstrokes.',
    price: 140000,
    discount_price: 115000,
    category_id: 'cat-3',
    category: DEMO_CATEGORIES[2],
    is_digital: false,
    stock: 3,
    is_featured: true,
    is_published: true,
    specifications: { 'Dimensions': '36 x 48 inches (91 x 122 cm)', 'Medium': 'Mixed Acrylic & Gold Leaf on Canvas', 'Finish': 'Satin UV Varnish' },
    images: [
      { id: 'img-2-1', product_id: 'prod-2', image_url: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=1000&auto=format&fit=crop&q=80', alt_text: 'Gold & Indigo Landscape', display_order: 1 },
    ],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-20',
    title: 'Whispering Hills — Scenic Valley Oil Landscape',
    slug: 'whispering-hills-landscape-canvas',
    description: 'Lush green valleys bathed in soft morning light, textured with palette knife layers.',
    price: 125000,
    discount_price: 99000,
    category_id: 'cat-3',
    category: DEMO_CATEGORIES[2],
    is_digital: false,
    stock: 4,
    is_featured: false,
    is_published: true,
    specifications: { 'Dimensions': '30 x 40 inches (76 x 101 cm)', 'Medium': 'Impasto Oil on Canvas' },
    images: [
      { id: 'img-20-1', product_id: 'prod-20', image_url: 'https://images.unsplash.com/photo-1580136579312-94651dfd596d?w=1000&auto=format&fit=crop&q=80', alt_text: 'Whispering Hills', display_order: 1 },
    ],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-21',
    title: 'Sunset Over Misty Pines — Nature Canvas Painting',
    slug: 'sunset-misty-pines-landscape',
    description: 'Vibrant orange, magenta, and crimson sunset sky casting warm reflections across pine forests.',
    price: 135000,
    discount_price: 110000,
    category_id: 'cat-3',
    category: DEMO_CATEGORIES[2],
    is_digital: false,
    stock: 5,
    is_featured: false,
    is_published: true,
    specifications: { 'Dimensions': '32 x 44 inches (81 x 111 cm)', 'Medium': 'Acrylic & Oil on Canvas' },
    images: [
      { id: 'img-21-1', product_id: 'prod-21', image_url: 'https://images.unsplash.com/photo-1549887534-1541e9326642?w=1000&auto=format&fit=crop&q=80', alt_text: 'Sunset Misty Pines', display_order: 1 },
    ],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-22',
    title: 'Azure Waters & Coastal Cliffs — Acrylic Seascape',
    slug: 'azure-waters-coastal-cliffs',
    description: 'Capturing dynamic ocean waves and rugged coastal rocks in deep turquoise and foam white.',
    price: 110000,
    discount_price: 89000,
    category_id: 'cat-3',
    category: DEMO_CATEGORIES[2],
    is_digital: false,
    stock: 6,
    is_featured: false,
    is_published: true,
    specifications: { 'Dimensions': '24 x 36 inches (60 x 91 cm)', 'Medium': 'Acrylic on Cotton Canvas' },
    images: [
      { id: 'img-22-1', product_id: 'prod-22', image_url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1000&auto=format&fit=crop&q=80', alt_text: 'Azure Waters', display_order: 1 },
    ],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-23',
    title: 'Autumn Gold Forest — Textured Woodland Landscape',
    slug: 'autumn-gold-forest-landscape',
    description: 'Rich amber and golden foliage in a serene woodland pathway painting.',
    price: 148000,
    discount_price: 122000,
    category_id: 'cat-3',
    category: DEMO_CATEGORIES[2],
    is_digital: false,
    stock: 2,
    is_featured: false,
    is_published: true,
    specifications: { 'Dimensions': '36 x 48 inches (91 x 122 cm)', 'Medium': 'Textured Oil Knife Work' },
    images: [
      { id: 'img-23-1', product_id: 'prod-23', image_url: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=1000&auto=format&fit=crop&q=80', alt_text: 'Autumn Gold Forest', display_order: 1 },
    ],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-24',
    title: 'Mountain Majesty at Dusk — Fine Art Scenic Canvas',
    slug: 'mountain-majesty-dusk-landscape',
    description: 'Panoramic mountain peaks standing tall under a twilight sky.',
    price: 165000,
    discount_price: 139000,
    category_id: 'cat-3',
    category: DEMO_CATEGORIES[2],
    is_digital: false,
    stock: 3,
    is_featured: false,
    is_published: true,
    specifications: { 'Dimensions': '40 x 60 inches (101 x 152 cm)', 'Medium': 'Fine Oil on Linen Canvas' },
    images: [
      { id: 'img-24-1', product_id: 'prod-24', image_url: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1000&auto=format&fit=crop&q=80', alt_text: 'Mountain Majesty', display_order: 1 },
    ],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-25',
    title: 'Reflections on the Lake — Serene Water Landscape',
    slug: 'reflections-lake-water-landscape',
    description: 'Glass-like water surface reflecting surrounding autumn trees and sky.',
    price: 105000,
    discount_price: 88000,
    category_id: 'cat-3',
    category: DEMO_CATEGORIES[2],
    is_digital: false,
    stock: 7,
    is_featured: false,
    is_published: true,
    specifications: { 'Dimensions': '24 x 32 inches (60 x 81 cm)', 'Medium': 'Acrylic & Oil Varnish' },
    images: [
      { id: 'img-25-1', product_id: 'prod-25', image_url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=1000&auto=format&fit=crop&q=80', alt_text: 'Reflections on the Lake', display_order: 1 },
    ],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-26',
    title: 'Golden Savannah Twilight — African Landscape Canvas',
    slug: 'golden-savannah-twilight-landscape',
    description: 'Vast golden grasslands under an iconic African sunset horizon.',
    price: 155000,
    discount_price: 129000,
    category_id: 'cat-3',
    category: DEMO_CATEGORIES[2],
    is_digital: false,
    stock: 4,
    is_featured: false,
    is_published: true,
    specifications: { 'Dimensions': '36 x 52 inches (91 x 132 cm)', 'Medium': 'Master Oil on Canvas' },
    images: [
      { id: 'img-26-1', product_id: 'prod-26', image_url: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1000&auto=format&fit=crop&q=80', alt_text: 'Golden Savannah Twilight', display_order: 1 },
    ],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },

  // SECTION 4: WALL ART & DECORATIVE PIECES / SCULPTURES (8 ITEMS)
  {
    id: 'prod-4',
    title: 'Botanical Harmony — Decorative Wall Painting (Hand-Painted)',
    slug: 'botanical-harmony-decorative-wall-painting',
    description: 'A large decorative wall artwork combining organic botanical forms with contemporary color palettes. Perfect centerpiece for living spaces and offices.',
    price: 95000,
    discount_price: 78000,
    category_id: 'cat-4',
    category: DEMO_CATEGORIES[3],
    is_digital: false,
    stock: 6,
    is_featured: true,
    is_published: true,
    specifications: { 'Dimensions': '40 x 40 inches (101 x 101 cm)', 'Style': 'Contemporary Decorative Art', 'Colors': 'Sage, Ochre, Cream' },
    images: [
      { id: 'img-4-1', product_id: 'prod-4', image_url: 'https://images.unsplash.com/photo-1579783901586-d88db74b4fe4?w=1000&auto=format&fit=crop&q=80', alt_text: 'Botanical Decorative Artwork', display_order: 1 },
    ],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-5',
    title: 'Ethereal Harmony — Hand-Sculpted Bronze & Clay Form',
    slug: 'ethereal-harmony-sculpture',
    description: 'A three-dimensional artistic sculpture exploring modern form, balance, and tactile material beauty. Hand-modeled by the artist.',
    price: 180000,
    discount_price: 155000,
    category_id: 'cat-4',
    category: DEMO_CATEGORIES[3],
    is_digital: false,
    stock: 2,
    is_featured: true,
    is_published: true,
    specifications: { 'Height': '18 inches (45 cm)', 'Material': 'Bronze Alloy & Polymer Clay Base', 'Edition': '1 of 3 Limited Sculptures' },
    images: [
      { id: 'img-5-1', product_id: 'prod-5', image_url: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=1000&auto=format&fit=crop&q=80', alt_text: 'Sculpture Preview', display_order: 1 },
    ],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-27',
    title: 'Tropical Sanctuary — Hand-Painted Wall Mural Piece',
    slug: 'tropical-sanctuary-wall-mural',
    description: 'Lush tropical palm fronds and muted terracotta motifs designed as an accent wall painting.',
    price: 130000,
    discount_price: 108000,
    category_id: 'cat-4',
    category: DEMO_CATEGORIES[3],
    is_digital: false,
    stock: 4,
    is_featured: false,
    is_published: true,
    specifications: { 'Dimensions': '48 x 48 inches (122 x 122 cm)', 'Medium': 'Emulsion & Gold Leaf' },
    images: [
      { id: 'img-27-1', product_id: 'prod-27', image_url: 'https://images.unsplash.com/photo-1576769267415-9642010aa962?w=1000&auto=format&fit=crop&q=80', alt_text: 'Tropical Sanctuary Wall Art', display_order: 1 },
    ],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-28',
    title: 'Geometric Bronze Form — Contemporary Decorative Sculpture',
    slug: 'geometric-bronze-form-sculpture',
    description: 'Modern geometric metallic form on dark mahogany pedestal.',
    price: 195000,
    discount_price: 168000,
    category_id: 'cat-4',
    category: DEMO_CATEGORIES[3],
    is_digital: false,
    stock: 2,
    is_featured: false,
    is_published: true,
    specifications: { 'Height': '22 inches (56 cm)', 'Material': 'Cast Bronze & Mahogany Base' },
    images: [
      { id: 'img-28-1', product_id: 'prod-28', image_url: 'https://images.unsplash.com/photo-1543857778-c4a1a3e0b2eb?w=1000&auto=format&fit=crop&q=80', alt_text: 'Geometric Bronze Form', display_order: 1 },
    ],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-29',
    title: 'Terracotta & Gold Relief — Textured Wall Art Piece',
    slug: 'terracotta-gold-relief-wall-art',
    description: 'Tactile wall relief combining terracotta clay textures with rich gold gilding.',
    price: 112000,
    discount_price: 94000,
    category_id: 'cat-4',
    category: DEMO_CATEGORIES[3],
    is_digital: false,
    stock: 5,
    is_featured: false,
    is_published: true,
    specifications: { 'Dimensions': '30 x 30 inches (76 x 76 cm)', 'Medium': 'Sculptural Clay & Gold Leaf' },
    images: [
      { id: 'img-29-1', product_id: 'prod-29', image_url: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=1000&auto=format&fit=crop&q=80', alt_text: 'Terracotta & Gold Relief', display_order: 1 },
    ],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-30',
    title: 'Abstract Botanical Fresco — Interior Wall Accent Painting',
    slug: 'abstract-botanical-fresco-wall-painting',
    description: 'Earthy plaster fresco technique rendering organic floral forms.',
    price: 128000,
    discount_price: 105000,
    category_id: 'cat-4',
    category: DEMO_CATEGORIES[3],
    is_digital: false,
    stock: 4,
    is_featured: false,
    is_published: true,
    specifications: { 'Dimensions': '36 x 48 inches (91 x 122 cm)', 'Medium': 'Mineral Fresco Pigments on Wood' },
    images: [
      { id: 'img-30-1', product_id: 'prod-30', image_url: 'https://images.unsplash.com/photo-1579783902263-6c7c2b3e83fa?w=1000&auto=format&fit=crop&q=80', alt_text: 'Abstract Botanical Fresco', display_order: 1 },
    ],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-31',
    title: 'Ceramic & Copper Balance — Sculptural Art Form',
    slug: 'ceramic-copper-balance-sculpture',
    description: 'Abstract tabletop sculpture handcrafted from fired ceramic and copper wire coils.',
    price: 140000,
    discount_price: 119000,
    category_id: 'cat-4',
    category: DEMO_CATEGORIES[3],
    is_digital: false,
    stock: 3,
    is_featured: false,
    is_published: true,
    specifications: { 'Height': '16 inches (40 cm)', 'Material': 'Fired Ceramic & Copper' },
    images: [
      { id: 'img-31-1', product_id: 'prod-31', image_url: 'https://images.unsplash.com/photo-1578925518470-4def7a0f08bb?w=1000&auto=format&fit=crop&q=80', alt_text: 'Ceramic & Copper Sculpture', display_order: 1 },
    ],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-32',
    title: 'Regal Heritage — Decorative Relief Wall Art',
    slug: 'regal-heritage-relief-wall-art',
    description: 'High-relief decorative wall carving with deep antiqued gold patina.',
    price: 165000,
    discount_price: 138000,
    category_id: 'cat-4',
    category: DEMO_CATEGORIES[3],
    is_digital: false,
    stock: 2,
    is_featured: false,
    is_published: true,
    specifications: { 'Dimensions': '40 x 50 inches (101 x 127 cm)', 'Medium': 'Resin Carving & Metallic Leaf' },
    images: [
      { id: 'img-32-1', product_id: 'prod-32', image_url: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=1000&auto=format&fit=crop&q=80', alt_text: 'Regal Heritage Relief', display_order: 1 },
    ],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  }
];

export const DEMO_PORTFOLIO: PortfolioProject[] = [
  {
    id: 'port-1',
    title: 'Royal Legacy — Oil Portrait Painting',
    slug: 'royal-legacy-oil-portrait',
    description: 'An expressive oil portrait painting crafted with rich layering and natural light direction. Focuses on physical likeness, emotional presence, and timeless character.',
    cover_image: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=1000&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=1000&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=1000&auto=format&fit=crop&q=80',
    ],
    category_id: 'pcat-1',
    category: DEMO_CATEGORIES[4],
    tools_used: ['Oil Paint', 'Linen Canvas', 'Brushes', 'Palette Knife'],
    client_name: 'Private Collector',
    date_completed: '2026-03-10',
    is_featured: true,
    is_published: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'port-2',
    title: 'Whispering Hills — Landscape Painting',
    slug: 'whispering-hills-landscape',
    description: 'A serene landscape painting capturing early morning mist rising over lush green valleys. Richly textured with impasto knife work and delicate color transitions.',
    cover_image: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=1000&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=1000&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1578926375605-eaf7559b1458?w=1000&auto=format&fit=crop&q=80',
    ],
    category_id: 'pcat-2',
    category: DEMO_CATEGORIES[5],
    tools_used: ['Acrylic Paint', 'Cotton Canvas', 'Varnish'],
    client_name: 'Lagos Fine Art Gallery',
    date_completed: '2026-02-14',
    is_featured: true,
    is_published: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'port-3',
    title: 'Moments in Solitude — Life-Image Painting',
    slug: 'moments-in-solitude-life-image',
    description: 'A deeply personal life-image painting capturing a quiet moment of reflection. Explores human expression, ambient light, and storytelling through color choices.',
    cover_image: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=1000&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=1000&auto=format&fit=crop&q=80',
    ],
    category_id: 'pcat-3',
    category: DEMO_CATEGORIES[6],
    tools_used: ['Oil on Board', 'Soft Brushes'],
    client_name: 'Private Studio Collection',
    date_completed: '2026-01-05',
    is_featured: true,
    is_published: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'port-4',
    title: 'Botanical Sanctuary — Painted Interior & Wall Art',
    slug: 'botanical-sanctuary-wall-art',
    description: 'Custom hand-painted interior wall mural created for a luxury residential living room. Features sweeping organic foliage, subtle gold accents, and serene muted tones.',
    cover_image: 'https://images.unsplash.com/photo-1582561424760-0321d75e81fa?w=1000&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1582561424760-0321d75e81fa?w=1000&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=1000&auto=format&fit=crop&q=80',
    ],
    category_id: 'pcat-4',
    category: DEMO_CATEGORIES[7],
    tools_used: ['Interior Emulsion', 'Gold Leaf', 'Detail Brushes'],
    client_name: 'Lekki Residential Villa',
    date_completed: '2025-11-20',
    is_featured: true,
    is_published: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'port-5',
    title: 'Form & Silhouette — Contemporary Sculpture',
    slug: 'form-silhouette-sculpture',
    description: 'A decorative sculptural art piece handcrafted from clay, bronze finish, and mahogany wood base. Blends modern geometric minimalism with tactile sculptural craft.',
    cover_image: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=1000&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1544717305-2782549b5136?w=1000&auto=format&fit=crop&q=80',
    ],
    category_id: 'pcat-5',
    category: DEMO_CATEGORIES[8],
    tools_used: ['Sculpting Clay', 'Bronze Alloy', 'Wood Chisels'],
    client_name: 'Artistic Works Exhibition',
    date_completed: '2025-10-15',
    is_featured: true,
    is_published: true,
    created_at: new Date().toISOString(),
  }
];

export const DEMO_SERVICES: ServiceItem[] = [
  {
    id: 'serv-1',
    title: 'Interior Painting',
    slug: 'interior-painting',
    description: 'Professional painting for residential and commercial interiors. We transform interior walls with premium color blending, smooth finishes, and artistic detail.',
    image_url: 'https://images.unsplash.com/photo-1562663474-6cbb3eaa4d14?w=800&auto=format&fit=crop&q=80',
    starting_price: 120000,
    delivery_time_days: 5,
    features: ['Custom Color Consultation', 'Surface Preparation & Priming', 'Premium Odorless Paint Application', 'Clean & Protection Guarantee'],
    is_active: true,
    created_at: new Date().toISOString(),
    artworks: [
      { id: 'art-1-1', service_id: 'serv-1', title: 'Minimalist Ochre Feature Wall', image_url: 'https://images.unsplash.com/photo-1562663474-6cbb3eaa4d14?w=800&auto=format&fit=crop&q=80', artist_id: 'usr-artist-1', artist_name: 'Elena Rostova', artist_avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100', artist_rating: 4.9, price: 125000, description: 'Textured warm ochre interior accent wall.' },
      { id: 'art-1-2', service_id: 'serv-1', title: 'Architectural Shadow & Bronze Wash', image_url: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=800&auto=format&fit=crop&q=80', artist_id: 'usr-artist-2', artist_name: 'Marcus Vance', artist_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100', artist_rating: 4.8, price: 160000, description: 'Sculptural wall wash with metallic bronze undertones.' },
      { id: 'art-1-3', service_id: 'serv-1', title: 'Lekki Villa Master Suite Wall', image_url: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800&auto=format&fit=crop&q=80', artist_id: 'usr-admin-master', artist_name: 'Abdulmajeed Olasunkanmi O. (Founder)', artist_avatar: '/founder.jpg', artist_rating: 5.0, price: 180000, description: 'Mastercrafted living space gradient wall painting.' },
      { id: 'art-1-4', service_id: 'serv-1', title: 'Nordic Sage & Linen Living Room', image_url: 'https://images.unsplash.com/photo-1582561424760-0321d75e81fa?w=800&auto=format&fit=crop&q=80', artist_id: 'usr-artist-1', artist_name: 'Elena Rostova', artist_avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100', artist_rating: 4.9, price: 130000, description: 'Calming sage green plaster finish.' },
      { id: 'art-1-5', service_id: 'serv-1', title: 'Terracotta Warmth Bedroom Feature', image_url: 'https://images.unsplash.com/photo-1578926375605-eaf7559b1458?w=800&auto=format&fit=crop&q=80', artist_id: 'usr-artist-3', artist_name: 'Amara Okafor', artist_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100', artist_rating: 4.9, price: 140000, description: 'Rich earthy terracotta wall glaze.' },
      { id: 'art-1-6', service_id: 'serv-1', title: 'Industrial Slate Lounge Accent', image_url: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=800&auto=format&fit=crop&q=80', artist_id: 'usr-artist-2', artist_name: 'Marcus Vance', artist_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100', artist_rating: 4.8, price: 155000, description: 'Deep slate grey matte finish.' },
      { id: 'art-1-7', service_id: 'serv-1', title: 'Gold Leaf Ceiling Inset', image_url: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=800&auto=format&fit=crop&q=80', artist_id: 'usr-admin-master', artist_name: 'Abdulmajeed Olasunkanmi O. (Founder)', artist_avatar: '/founder.jpg', artist_rating: 5.0, price: 210000, description: 'Hand-gilded gold leaf ceiling trim.' }
    ]
  },
  {
    id: 'serv-2',
    title: 'Exterior Painting',
    slug: 'exterior-painting',
    description: 'Weather-resistant exterior wall painting that protects building surfaces while giving facades, gates, and exterior structures an elegant artistic aesthetic.',
    image_url: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=800&auto=format&fit=crop&q=80',
    starting_price: 180000,
    delivery_time_days: 7,
    features: ['Weatherproof UV Coating', 'Pressure Wall Cleaning', 'Durable Acrylic Exterior Emulsion', 'Multi-Year Finish Warranty'],
    is_active: true,
    created_at: new Date().toISOString(),
    artworks: [
      { id: 'art-2-1', service_id: 'serv-2', title: 'Modern Villa Facade Coating', image_url: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=800&auto=format&fit=crop&q=80', artist_id: 'usr-admin-master', artist_name: 'Abdulmajeed Olasunkanmi O. (Founder)', artist_avatar: '/founder.jpg', artist_rating: 5.0, price: 250000, description: 'Weather-sealed luxury villa facade.' },
      { id: 'art-2-2', service_id: 'serv-2', title: 'Geometric Exterior Gate Painting', image_url: 'https://images.unsplash.com/photo-1562663474-6cbb3eaa4d14?w=800&auto=format&fit=crop&q=80', artist_id: 'usr-artist-2', artist_name: 'Marcus Vance', artist_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100', artist_rating: 4.8, price: 190000, description: 'Heavy-duty matte black and copper gate finish.' },
      { id: 'art-2-3', service_id: 'serv-2', title: 'Coastal UV Shield Exterior Wall', image_url: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=800&auto=format&fit=crop&q=80', artist_id: 'usr-artist-4', artist_name: 'Tariq Hassan', artist_avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100', artist_rating: 4.7, price: 210000, description: 'Salt-spray resistant exterior latex Coating.' },
      { id: 'art-2-4', service_id: 'serv-2', title: 'Textured Stucco Exterior Facade', image_url: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800&auto=format&fit=crop&q=80', artist_id: 'usr-artist-1', artist_name: 'Elena Rostova', artist_avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100', artist_rating: 4.9, price: 200000, description: 'Warm sand textured exterior stucco finish.' },
      { id: 'art-2-5', service_id: 'serv-2', title: 'Contemporary Charcoal Exterior Compound', image_url: 'https://images.unsplash.com/photo-1582561424760-0321d75e81fa?w=800&auto=format&fit=crop&q=80', artist_id: 'usr-admin-master', artist_name: 'Abdulmajeed Olasunkanmi O. (Founder)', artist_avatar: '/founder.jpg', artist_rating: 5.0, price: 280000, description: 'Architectural charcoal dark exterior theme.' },
      { id: 'art-2-6', service_id: 'serv-2', title: 'Veranda Accent Pillar Detailing', image_url: 'https://images.unsplash.com/photo-1578926375605-eaf7559b1458?w=800&auto=format&fit=crop&q=80', artist_id: 'usr-artist-3', artist_name: 'Amara Okafor', artist_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100', artist_rating: 4.9, price: 180000, description: 'Hand-detailed stone pillar finish.' },
      { id: 'art-2-7', service_id: 'serv-2', title: 'Commercial Plaza Facade Renovation', image_url: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=800&auto=format&fit=crop&q=80', artist_id: 'usr-artist-4', artist_name: 'Tariq Hassan', artist_avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100', artist_rating: 4.7, price: 320000, description: 'Commercial building exterior weathercoating.' }
    ]
  },
  {
    id: 'serv-3',
    title: 'Interior Decoration',
    slug: 'interior-decoration',
    description: 'Artistic interior space decoration combining hand-painted accents, color harmonies, lighting ambiance, and decorative wall placements.',
    image_url: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800&auto=format&fit=crop&q=80',
    starting_price: 150000,
    delivery_time_days: 7,
    features: ['Full Room Moodboard Design', 'Artwork Placement & Hanging', 'Color Palette Styling', 'Custom Accent Wall Design'],
    is_active: true,
    created_at: new Date().toISOString(),
    artworks: [
      { id: 'art-3-1', service_id: 'serv-3', title: 'Contemporary Living Room Moodboard', image_url: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800&auto=format&fit=crop&q=80', artist_id: 'usr-artist-1', artist_name: 'Elena Rostova', artist_avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100', artist_rating: 4.9, price: 150000, description: 'Full room color palette design.' },
      { id: 'art-3-2', service_id: 'serv-3', title: 'Gallery Wall Arrangement Service', image_url: 'https://images.unsplash.com/photo-1582561424760-0321d75e81fa?w=800&auto=format&fit=crop&q=80', artist_id: 'usr-admin-master', artist_name: 'Abdulmajeed Olasunkanmi O. (Founder)', artist_avatar: '/founder.jpg', artist_rating: 5.0, price: 180000, description: 'Professional artwork hanging and layout.' },
      { id: 'art-3-3', service_id: 'serv-3', title: 'Minimalist Dining Space Styling', image_url: 'https://images.unsplash.com/photo-1562663474-6cbb3eaa4d14?w=800&auto=format&fit=crop&q=80', artist_id: 'usr-artist-2', artist_name: 'Marcus Vance', artist_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100', artist_rating: 4.8, price: 165000, description: 'Tabletop and wall decor coordination.' },
      { id: 'art-3-4', service_id: 'serv-3', title: 'Lounge Lighting & Art Ambiance', image_url: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=800&auto=format&fit=crop&q=80', artist_id: 'usr-artist-3', artist_name: 'Amara Okafor', artist_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100', artist_rating: 4.9, price: 200000, description: 'Ambiance setup and accent lighting.' },
      { id: 'art-3-5', service_id: 'serv-3', title: 'Executive Home Office Decor', image_url: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=800&auto=format&fit=crop&q=80', artist_id: 'usr-admin-master', artist_name: 'Abdulmajeed Olasunkanmi O. (Founder)', artist_avatar: '/founder.jpg', artist_rating: 5.0, price: 220000, description: 'Professional office aesthetic transformation.' },
      { id: 'art-3-6', service_id: 'serv-3', title: 'Bohemian Bedroom Textile Decor', image_url: 'https://images.unsplash.com/photo-1578926375605-eaf7559b1458?w=800&auto=format&fit=crop&q=80', artist_id: 'usr-artist-4', artist_name: 'Tariq Hassan', artist_avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100', artist_rating: 4.7, price: 140000, description: 'Boho aesthetic room styling.' }
    ]
  },
  {
    id: 'serv-4',
    title: 'Landscape Painting',
    slug: 'landscape-painting-service',
    description: 'Custom commissioned landscape paintings capturing your favorite natural locations, scenic memories, gardens, or serene vistas on premium canvas.',
    image_url: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=800&auto=format&fit=crop&q=80',
    starting_price: 95000,
    delivery_time_days: 7,
    features: ['Original Canvas Painting', 'Custom Dimensions Available', 'High-Detail Natural Scenery', 'Certificate of Authenticity'],
    is_active: true,
    created_at: new Date().toISOString(),
    artworks: [
      { id: 'art-4-1', service_id: 'serv-4', title: 'Mist Over Verdant Valley', image_url: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=800&auto=format&fit=crop&q=80', artist_id: 'usr-admin-master', artist_name: 'Abdulmajeed Olasunkanmi O. (Founder)', artist_avatar: '/founder.jpg', artist_rating: 5.0, price: 110000, description: 'Impasto mountain landscape study.' },
      { id: 'art-4-2', service_id: 'serv-4', title: 'Golden Hour Coastal Cliffs', image_url: 'https://images.unsplash.com/photo-1578926375605-eaf7559b1458?w=800&auto=format&fit=crop&q=80', artist_id: 'usr-artist-1', artist_name: 'Elena Rostova', artist_avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100', artist_rating: 4.9, price: 120000, description: 'Seaside sunset landscape oil painting.' },
      { id: 'art-4-3', service_id: 'serv-4', title: 'Autumn Forest Sunlight Study', image_url: 'https://images.unsplash.com/photo-1582561424760-0321d75e81fa?w=800&auto=format&fit=crop&q=80', artist_id: 'usr-artist-2', artist_name: 'Marcus Vance', artist_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100', artist_rating: 4.8, price: 95000, description: 'Atmospheric forest landscape.' },
      { id: 'art-4-4', service_id: 'serv-4', title: 'Desert Oasis Under Stars', image_url: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=800&auto=format&fit=crop&q=80', artist_id: 'usr-artist-3', artist_name: 'Amara Okafor', artist_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100', artist_rating: 4.9, price: 130000, description: 'Night desert landscape painting.' },
      { id: 'art-4-5', service_id: 'serv-4', title: 'Riverbank Calm Morning', image_url: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800&auto=format&fit=crop&q=80', artist_id: 'usr-admin-master', artist_name: 'Abdulmajeed Olasunkanmi O. (Founder)', artist_avatar: '/founder.jpg', artist_rating: 5.0, price: 150000, description: 'Reflective morning landscape oil on canvas.' },
      { id: 'art-4-6', service_id: 'serv-4', title: 'Urban Garden Landscape', image_url: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=800&auto=format&fit=crop&q=80', artist_id: 'usr-artist-4', artist_name: 'Tariq Hassan', artist_avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100', artist_rating: 4.7, price: 105000, description: 'Contemporary garden painting.' }
    ]
  },
  {
    id: 'serv-5',
    title: 'Portrait Painting',
    slug: 'portrait-painting-service',
    description: 'Bespoke hand-painted oil or acrylic portraits created from your personal photographs. Captures likeness, personality, and human emotion on canvas.',
    image_url: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=800&auto=format&fit=crop&q=80',
    starting_price: 110000,
    delivery_time_days: 10,
    features: ['Hand-Painted from Photo', 'Multiple Subject Options', 'Oil or Acrylic Medium', 'Framing Consultation Included'],
    is_active: true,
    created_at: new Date().toISOString(),
    artworks: [
      { id: 'art-5-1', service_id: 'serv-5', title: 'Grace & Elegance — Oil Portrait Study', image_url: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=800&auto=format&fit=crop&q=80', artist_id: 'usr-admin-master', artist_name: 'Abdulmajeed Olasunkanmi O. (Founder)', artist_avatar: '/founder.jpg', artist_rating: 5.0, price: 125000, description: 'Classic oil portrait on stretched linen.' },
      { id: 'art-5-2', service_id: 'serv-5', title: 'Twilight Reverie Portrait', image_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800&auto=format&fit=crop&q=80', artist_id: 'usr-artist-1', artist_name: 'Elena Rostova', artist_avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100', artist_rating: 4.9, price: 135000, description: 'Emotive portrait with classical glazing.' },
      { id: 'art-5-3', service_id: 'serv-5', title: 'Figurative Bronze Relief Portrait', image_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&auto=format&fit=crop&q=80', artist_id: 'usr-artist-2', artist_name: 'Marcus Vance', artist_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100', artist_rating: 4.8, price: 170000, description: '3D clay relief profile portrait.' },
      { id: 'art-5-4', service_id: 'serv-5', title: 'Royal Legacy Family Heirloom Portrait', image_url: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=800&auto=format&fit=crop&q=80', artist_id: 'usr-admin-master', artist_name: 'Abdulmajeed Olasunkanmi O. (Founder)', artist_avatar: '/founder.jpg', artist_rating: 5.0, price: 190000, description: 'Regal oil canvas family portrait.' },
      { id: 'art-5-5', service_id: 'serv-5', title: 'Serene Radiance — Pastel & Oil Study', image_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&auto=format&fit=crop&q=80', artist_id: 'usr-artist-3', artist_name: 'Amara Okafor', artist_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100', artist_rating: 4.9, price: 145000, description: 'Soft pastel glow portrait.' },
      { id: 'art-5-6', service_id: 'serv-5', title: 'Maiden in Golden Light', image_url: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=800&auto=format&fit=crop&q=80', artist_id: 'usr-artist-1', artist_name: 'Elena Rostova', artist_avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100', artist_rating: 4.9, price: 130000, description: 'Warm ochre lighting portrait study.' },
      { id: 'art-5-7', service_id: 'serv-5', title: 'Visionary Spirit Character Study', image_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&auto=format&fit=crop&q=80', artist_id: 'usr-artist-4', artist_name: 'Tariq Hassan', artist_avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100', artist_rating: 4.7, price: 115000, description: 'Expressive acrylic portrait on canvas.' }
    ]
  },
  {
    id: 'serv-6',
    title: 'Life-Image Painting',
    slug: 'life-image-painting-service',
    description: 'Capturing authentic human moments, cultural heritage, and expressive life scenes through vivid painterly storytelling.',
    image_url: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=800&auto=format&fit=crop&q=80',
    starting_price: 100000,
    delivery_time_days: 8,
    features: ['Expressive Human Storytelling', 'Custom Lighting Effects', 'Museum-Grade Canvas', 'Signed by Artist'],
    is_active: true,
    created_at: new Date().toISOString(),
    artworks: [
      { id: 'art-6-1', service_id: 'serv-6', title: 'Reflective Solitude Study', image_url: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=800&auto=format&fit=crop&q=80', artist_id: 'usr-admin-master', artist_name: 'Abdulmajeed Olasunkanmi O. (Founder)', artist_avatar: '/founder.jpg', artist_rating: 5.0, price: 110000, description: 'Painterly human storytelling.' },
      { id: 'art-6-2', service_id: 'serv-6', title: 'Market Day Cultural Scene', image_url: 'https://images.unsplash.com/photo-1562663474-6cbb3eaa4d14?w=800&auto=format&fit=crop&q=80', artist_id: 'usr-artist-4', artist_name: 'Tariq Hassan', artist_avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100', artist_rating: 4.7, price: 140000, description: 'Vibrant cultural heritage painting.' },
      { id: 'art-6-3', service_id: 'serv-6', title: 'Stolen Moments Coffee Shop', image_url: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=800&auto=format&fit=crop&q=80', artist_id: 'usr-artist-2', artist_name: 'Marcus Vance', artist_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100', artist_rating: 4.8, price: 125000, description: 'Ambient lighting daily life study.' },
      { id: 'art-6-4', service_id: 'serv-6', title: 'The Weaver’s Hands Heritage', image_url: 'https://images.unsplash.com/photo-1578926375605-eaf7559b1458?w=800&auto=format&fit=crop&q=80', artist_id: 'usr-artist-3', artist_name: 'Amara Okafor', artist_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100', artist_rating: 4.9, price: 160000, description: 'Textured oil painting of artisan craft.' },
      { id: 'art-6-5', service_id: 'serv-6', title: 'Urban Commute Morning Light', image_url: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=800&auto=format&fit=crop&q=80', artist_id: 'usr-admin-master', artist_name: 'Abdulmajeed Olasunkanmi O. (Founder)', artist_avatar: '/founder.jpg', artist_rating: 5.0, price: 130000, description: 'Dynamic street life painting.' },
      { id: 'art-6-6', service_id: 'serv-6', title: 'Traditional Dance Performance', image_url: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800&auto=format&fit=crop&q=80', artist_id: 'usr-artist-1', artist_name: 'Elena Rostova', artist_avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100', artist_rating: 4.9, price: 180000, description: 'Expressive movement study.' }
    ]
  },
  {
    id: 'serv-7',
    title: 'Wall Art & Murals',
    slug: 'wall-art-murals',
    description: 'Large-scale hand-painted wall art and decorative murals designed specifically for feature walls in homes, restaurants, studios, and offices.',
    image_url: 'https://images.unsplash.com/photo-1582561424760-0321d75e81fa?w=800&auto=format&fit=crop&q=80',
    starting_price: 200000,
    delivery_time_days: 6,
    features: ['Site Inspection & Sketching', 'Custom Mural Concepts', 'Durable Wall Pigments', 'Protective Varnish Clearcoat'],
    is_active: true,
    created_at: new Date().toISOString(),
    artworks: [
      { id: 'art-7-1', service_id: 'serv-7', title: 'Botanical Sanctuary Custom Mural', image_url: 'https://images.unsplash.com/photo-1582561424760-0321d75e81fa?w=800&auto=format&fit=crop&q=80', artist_id: 'usr-admin-master', artist_name: 'Abdulmajeed Olasunkanmi O. (Founder)', artist_avatar: '/founder.jpg', artist_rating: 5.0, price: 250000, description: 'Lush tropical hand-painted wall mural.' },
      { id: 'art-7-2', service_id: 'serv-7', title: 'Geometric Relief Wall Feature', image_url: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=800&auto=format&fit=crop&q=80', artist_id: 'usr-artist-2', artist_name: 'Marcus Vance', artist_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100', artist_rating: 4.8, price: 280000, description: '3D clay and metallic leaf wall feature.' },
      { id: 'art-7-3', service_id: 'serv-7', title: 'Tropical Palm Breeze Restaurant Mural', image_url: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=800&auto=format&fit=crop&q=80', artist_id: 'usr-artist-3', artist_name: 'Amara Okafor', artist_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100', artist_rating: 4.9, price: 220000, description: 'Vibrant dining room tropical wall artwork.' },
      { id: 'art-7-4', service_id: 'serv-7', title: 'Impasto Flower Canopy Feature', image_url: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=800&auto=format&fit=crop&q=80', artist_id: 'usr-artist-1', artist_name: 'Elena Rostova', artist_avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100', artist_rating: 4.9, price: 240000, description: 'Textured oil floral wall mural.' },
      { id: 'art-7-5', service_id: 'serv-7', title: 'Abstract Gold Leaf Wall Statement', image_url: 'https://images.unsplash.com/photo-1578926375605-eaf7559b1458?w=800&auto=format&fit=crop&q=80', artist_id: 'usr-admin-master', artist_name: 'Abdulmajeed Olasunkanmi O. (Founder)', artist_avatar: '/founder.jpg', artist_rating: 5.0, price: 300000, description: 'Executive boardroom gold leaf wall mural.' },
      { id: 'art-7-6', service_id: 'serv-7', title: 'Modernist Line Art Cafe Wall', image_url: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=800&auto=format&fit=crop&q=80', artist_id: 'usr-artist-4', artist_name: 'Tariq Hassan', artist_avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100', artist_rating: 4.7, price: 210000, description: 'Sleek black line art mural.' },
      { id: 'art-7-7', service_id: 'serv-7', title: 'Terracotta Fresco Hotel Lobby Wall', image_url: 'https://images.unsplash.com/photo-1562663474-6cbb3eaa4d14?w=800&auto=format&fit=crop&q=80', artist_id: 'usr-artist-2', artist_name: 'Marcus Vance', artist_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100', artist_rating: 4.8, price: 350000, description: 'Hand-carved plaster wall fresco.' }
    ]
  },
  {
    id: 'serv-8',
    title: 'Decorative Painting',
    slug: 'decorative-painting-service',
    description: 'Artistic faux finishes, gold leaf detailing, textured wall effects, and custom decorative canvas pieces tailored to elevate space aesthetics.',
    image_url: 'https://images.unsplash.com/photo-1578926375605-eaf7559b1458?w=800&auto=format&fit=crop&q=80',
    starting_price: 85000,
    delivery_time_days: 5,
    features: ['Textured Impasto Finishes', 'Gold/Silver Leaf Accents', 'Custom Color Matching', 'Ready to Display'],
    is_active: true,
    created_at: new Date().toISOString(),
    artworks: [
      { id: 'art-8-1', service_id: 'serv-8', title: 'Textured Impasto Gold Accent', image_url: 'https://images.unsplash.com/photo-1578926375605-eaf7559b1458?w=800&auto=format&fit=crop&q=80', artist_id: 'usr-admin-master', artist_name: 'Abdulmajeed Olasunkanmi O. (Founder)', artist_avatar: '/founder.jpg', artist_rating: 5.0, price: 95000, description: 'Textured impasto and gold accents.' },
      { id: 'art-8-2', service_id: 'serv-8', title: 'Faux Aged Bronze Finish', image_url: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=800&auto=format&fit=crop&q=80', artist_id: 'usr-artist-2', artist_name: 'Marcus Vance', artist_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100', artist_rating: 4.8, price: 110000, description: 'Authentic metallic faux finish.' },
      { id: 'art-8-3', service_id: 'serv-8', title: 'Silver Leaf Geometric Detail', image_url: 'https://images.unsplash.com/photo-1582561424760-0321d75e81fa?w=800&auto=format&fit=crop&q=80', artist_id: 'usr-artist-1', artist_name: 'Elena Rostova', artist_avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100', artist_rating: 4.9, price: 130000, description: 'Intricate silver leaf detailing.' },
      { id: 'art-8-4', service_id: 'serv-8', title: 'Earthy Clay Plaster Accent', image_url: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800&auto=format&fit=crop&q=80', artist_id: 'usr-artist-3', artist_name: 'Amara Okafor', artist_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100', artist_rating: 4.9, price: 85000, description: 'Organic clay textural wall effect.' },
      { id: 'art-8-5', service_id: 'serv-8', title: 'Gilded Minimalist Panel', image_url: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=800&auto=format&fit=crop&q=80', artist_id: 'usr-admin-master', artist_name: 'Abdulmajeed Olasunkanmi O. (Founder)', artist_avatar: '/founder.jpg', artist_rating: 5.0, price: 150000, description: 'Premium decorative gold canvas.' },
      { id: 'art-8-6', service_id: 'serv-8', title: 'Abstract Patina Wall Relief', image_url: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=800&auto=format&fit=crop&q=80', artist_id: 'usr-artist-4', artist_name: 'Tariq Hassan', artist_avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100', artist_rating: 4.7, price: 120000, description: 'Patina-inspired wall decor.' }
    ]
  },
  {
    id: 'serv-9',
    title: 'Custom Artwork Commissions',
    slug: 'custom-artwork-commissions',
    description: 'Have a specific idea or artistic vision? Work directly with artist Abdulmajeed Olasunkanmi O. to bring your unique concept to life on canvas.',
    image_url: 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=800&auto=format&fit=crop&q=80',
    starting_price: 130000,
    delivery_time_days: 10,
    features: ['1-on-1 Artist Consultation', 'Preliminary Concept Sketches', 'Regular Progress Updates', 'Custom Framing & Delivery'],
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'serv-10',
    title: 'Sculpture & Artistic Works',
    slug: 'sculpture-artistic-works',
    description: 'Three-dimensional artistic sculptures, clay/bronze forms, and decorative sculptural pieces to add physical depth and elegance to spaces.',
    image_url: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=800&auto=format&fit=crop&q=80',
    starting_price: 160000,
    delivery_time_days: 14,
    features: ['Clay & Metal Form Modeling', 'Custom Base & Mounts', 'Unique Limited Piece', 'Handcrafted Authenticity'],
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'serv-11',
    title: 'Graphic Design & Visual Media',
    slug: 'graphic-design-visual-media',
    description: 'Secondary creative service providing digital illustration, graphic artwork, and visual media branding tailored for art catalogs and creative ventures.',
    image_url: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=800&auto=format&fit=crop&q=80',
    starting_price: 50000,
    delivery_time_days: 4,
    features: ['Digital Illustration Vectors', 'Art Exhibition Catalog Layouts', 'High-Res Digital Files', 'Commercial Usage Rights'],
    is_active: true,
    created_at: new Date().toISOString(),
  }
];

export const DEMO_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    product_id: 'prod-1',
    user_id: 'user-1',
    user_name: 'Chidi O.',
    rating: 5,
    comment: 'The oil portrait painting exceeded my expectations! The depth of color and texture on canvas gives my living room an elevated, artistic soul. Abdulmajeed is a true master.',
    is_verified_purchase: true,
    status: 'approved',
    created_at: '2026-06-14T10:30:00Z',
  },
  {
    id: 'rev-2',
    product_id: 'prod-2',
    user_id: 'user-2',
    user_name: 'Amina B.',
    rating: 5,
    comment: 'The gold leaf and indigo landscape painting looks breathtaking in person. Safely delivered in a wood frame with a signed certificate. Highly recommend SK Artwork!',
    is_verified_purchase: true,
    status: 'approved',
    created_at: '2026-07-02T14:15:00Z',
  }
];

export const DEMO_ORDERS: Order[] = [
  {
    id: 'ord-1001',
    order_number: 'SK-2026-8841',
    user_id: 'user-1',
    customer_email: 'chidi.o@example.com',
    customer_name: 'Chidi Okonkwo',
    total_amount: 125000,
    discount_amount: 30000,
    delivery_fee: 3500,
    net_amount: 98500,
    order_status: 'Completed',
    payment_status: 'Paid',
    payment_reference: 'PST_ref_994821',
    payment_provider: 'paystack',
    items: [
      {
        id: 'oi-1',
        order_id: 'ord-1001',
        product_id: 'prod-1',
        product_title: 'Grace & Elegance — Oil Portrait Painting (Canvas Edition)',
        price: 95000,
        quantity: 1,
        is_digital: false
      }
    ],
    created_at: '2026-08-01T11:20:00Z',
    updated_at: '2026-08-01T11:22:00Z',
  },
  {
    id: 'ord-1002',
    order_number: 'SK-2026-9102',
    user_id: 'user-2',
    customer_email: 'amina.b@example.com',
    customer_name: 'Amina Bello',
    total_amount: 140000,
    discount_amount: 25000,
    delivery_fee: 3500,
    net_amount: 118500,
    order_status: 'Shipped',
    payment_status: 'Paid',
    payment_reference: 'PST_ref_102837',
    payment_provider: 'paystack',
    items: [
      {
        id: 'oi-2',
        order_id: 'ord-1002',
        product_id: 'prod-2',
        product_title: 'Horizon of Gold & Indigo — Landscape Artwork',
        price: 115000,
        quantity: 1,
        is_digital: false
      }
    ],
    created_at: '2026-08-10T16:45:00Z',
    updated_at: '2026-08-11T09:10:00Z',
  }
];
